### ISSUE TITLE
Getting - while using minus operator

### ISSUE THREAD

**Issue by electronic-heartbreak** [codyseibert/vue-calculator#5]
Hello,

I have followed your tutorial on how to make this calculator a long time ago.
Only now when i want ot re-use it I get some weird output by using the minus operator:
If I do for example 5-2 I get -3. How Do i fix this?
Kind regards.

**Comment by mhoumann87** [comment]
You will need to switch the previous and current in the equal function. You will also have a problem with divide.

```
equal() {
this.current = `${this.operator(
    parseFloat(this.previous),
    parseFloat(this.current)
)};
```
